export const SOURCES_DATABASE = {
  apis: {
    anime: [
      { name: 'AniList', url: 'https://alistapi.gg', type: 'graphql', reliability: 0.85 },
      { name: 'Jikan (MyAnimeList API)', url: 'https://api.jikan.moe/v4', type: 'rest', reliability: 0.85 },
      { name: 'Kitsu', url: 'https://kitsu.io/api/edge', type: 'json:api', reliability: 0.85 },
      { name: 'SIMKL', url: 'https://api.simkl.com', type: 'rest', reliability: 0.75 },
      { name: 'The Movie Database (TMDB)', url: 'https://api.themoviedb.org/3', type: 'rest', reliability: 0.85 },
      { name: 'TVmaze', url: 'https://api.tvmaze.com', type: 'rest', reliability: 0.75 },
      { name: 'Trakt', url: 'https://api.trakt.tv', type: 'rest', reliability: 0.75 },
      { name: 'MyAnimeList', url: 'https://myanimelist.net/apibest', type: 'rest', reliability: 0.85 },
      { name: 'AniAPI', url: 'https://aniapi.com.br/api', type: 'rest', reliability: 0.7 },
      { name: 'TraceMoe', url: 'https://api.trace.moe', type: 'rest', reliability: 0.7 },
      { name: 'AnimeChan', url: 'https://animechan.vercel.app/api', type: 'rest', reliability: 0.5 },
      { name: 'AnimeThemes', url: 'https://animethemes.moe/api', type: 'rest', reliability: 0.7 },
      { name: 'LiveChart', url: 'https://api.livechart.me/api/v1', type: 'rest', reliability: 0.75 },
      { name: 'AniChart', url: 'https://anichart.net/api', type: 'rest', reliability: 0.7 },
      { name: 'Waifu.im', url: 'https://api.waifu.im', type: 'rest', reliability: 0.5 },
      { name: 'NHK Program API', url: 'https://api.nhk.or.jp/nodata', type: 'rest', reliability: 0.9 },
      { name: 'Media Arts DB', url: 'https://mediaarts-db.bunka.go.jp', type: 'rest', reliability: 0.9 },
      { name: 'Annict', url: 'https://api.annict.com/v1', type: 'rest', reliability: 0.8 },
      { name: 'ShangriLa', url: 'https://api.sangrograph.com', type: 'graphql', reliability: 0.7 },
      { name: 'Shikimori', url: 'https://shikimori.com/api', type: 'rest', reliability: 0.8 },
      { name: 'AniDB', url: 'https://api.anidb.net:9001', type: 'rest', reliability: 0.85 },
      { name: 'Anime News Network API', url: 'https://www.animenewsnetwork.com/encyclopedia/reports.xml', type: 'xml', reliability: 0.85 },
      { name: 'notify.moe', url: 'https://notify.moe/api', type: 'rest', reliability: 0.75 },
      { name: 'OtakuMode', url: 'https://otakumode.com/api', type: 'rest', reliability: 0.6 },
    ],
    manga: [
      { name: 'MangaDex', url: 'https://api.mangadex.org', type: 'rest', reliability: 0.85 },
      { name: 'Comick', url: 'https://api.comick.fun', type: 'rest', reliability: 0.8 },
      { name: 'MAL Scraper', url: 'https://myanimelist.net', type: 'scraper', reliability: 0.75 },
      { name: 'OtakuMode Manga', url: 'https://otakumode.com/manga-api', type: 'rest', reliability: 0.6 },
      { name: 'Manga Plus', url: 'https://mangaplus.shueisha.co.jp/api', type: 'rest', reliability: 0.85 },
      { name: 'Crunchyroll Manga', url: 'https://manga.crunchyroll.com/api', type: 'rest', reliability: 0.8 },
      { name: 'Bato.to', url: 'https://bato.to/api/v3', type: 'rest', reliability: 0.7 },
      { name: 'MangaUpdates', url: 'https://www.mangaupdates.com/api', type: 'rest', reliability: 0.75 },
      { name: 'Novel Updates', url: 'https://www.novelupdates.com/api', type: 'rest', reliability: 0.7 },
      { name: 'J-Novel Club API', url: 'https://api.j-novel.club', type: 'rest', reliability: 0.8 },
    ],
    manhwa: [
      { name: 'Naver Webtoon API', url: 'https://webtoon.naver.com/api', type: 'rest', reliability: 0.85 },
      { name: 'Kakao Page API', url: 'https://page.kakao.com/api', type: 'rest', reliability: 0.85 },
      { name: 'WEBTOON API', url: 'https://www.webtoons.com/api', type: 'rest', reliability: 0.85 },
      { name: 'Tapas', url: 'https://tapas.io/api', type: 'rest', reliability: 0.75 },
      { name: 'Manta', url: 'https://manta.net/api', type: 'rest', reliability: 0.75 },
      { name: 'Lezhin', url: 'https://www.lezhin.com/api', type: 'rest', reliability: 0.7 },
      { name: 'Tappytoon', url: 'https://tappytoon.com/api', type: 'rest', reliability: 0.7 },
      { name: 'Toomics', url: 'https://toomics.com/api', type: 'rest', reliability: 0.7 },
      { name: 'MrBlue', url: 'https://mrblue.com/api', type: 'rest', reliability: 0.7 },
      { name: 'Kakao Webtoon', url: 'https://webtoon.kakao.com/api', type: 'rest', reliability: 0.8 },
    ],
    streaming: [
      { name: 'Crunchyroll API', url: 'https://api.crunchyroll.com', type: 'rest', reliability: 0.9 },
      { name: 'Netflix', url: 'https://netflix.com', type: 'web', reliability: 0.9 },
      { name: 'Disney+', url: 'https://disneyplus.com', type: 'web', reliability: 0.9 },
      { name: 'Hulu', url: 'https://hulu.com', type: 'web', reliability: 0.9 },
      { name: 'Prime Video', url: 'https://primevideo.com', type: 'web', reliability: 0.9 },
      { name: 'HIDIVE', url: 'https://hidive.com/api', type: 'rest', reliability: 0.85 },
      { name: 'VRV', url: 'https://vrv.co/api', type: 'rest', reliability: 0.8 },
      { name: 'Tubi', url: 'https://tubi.tv/api', type: 'rest', reliability: 0.7 },
      { name: 'Pluto TV', url: 'https://pluto.tv/api', type: 'rest', reliability: 0.7 },
      { name: 'RetroCrush', url: 'https://retrocrush.tv/api', type: 'rest', reliability: 0.7 },
      { name: 'Bilibili', url: 'https://api.bilibili.com', type: 'rest', reliability: 0.8 },
      { name: 'iQIYI', url: 'https://iq.com/api', type: 'rest', reliability: 0.75 },
      { name: 'WeTV', url: 'https://wetv.vip/api', type: 'rest', reliability: 0.75 },
      { name: 'Viu', url: 'https://viu.com/api', type: 'rest', reliability: 0.7 },
      { name: 'Viki', url: 'https://www.viki.com/api', type: 'rest', reliability: 0.75 },
      { name: 'Anime-Planet Streaming', url: 'https://anime-planet.com/watch', type: 'web', reliability: 0.7 },
      { name: '9Anime', url: 'https://9anime.to/api', type: 'rest', reliability: 0.5 },
      { name: 'Gogoanime', url: 'https://gogoanime.ai/api', type: 'rest', reliability: 0.5 },
      { name: 'Kissanime', url: 'https://kissanime.com/api', type: 'rest', reliability: 0.5 },
      { name: 'AnimePahe', url: 'https://animepahe.com/api', type: 'rest', reliability: 0.5 },
      { name: 'Animixplay', url: 'https://animixplay.to/api', type: 'rest', reliability: 0.5 },
      { name: 'Vidstreaming', url: 'https://vidstreaming.io/api', type: 'rest', reliability: 0.5 },
      { name: 'AllAnime', url: 'https://allanime.site/api', type: 'rest', reliability: 0.5 },
    ],
    film: [
      { name: 'IMDb API', url: 'https://www.imdb.com/interfaces', type: 'rest', reliability: 0.9 },
      { name: 'The Movie Database (TMDB)', url: 'https://api.themoviedb.org/3', type: 'rest', reliability: 0.85 },
      { name: 'OMDb API', url: 'https://www.omdbapi.com', type: 'rest', reliability: 0.8 },
      { name: 'Rotten Tomatoes', url: 'https://www.rottentomatoes.com/api', type: 'rest', reliability: 0.85 },
      { name: 'Letterboxd', url: 'https://letterboxd.com/data', type: 'rest', reliability: 0.8 },
      { name: 'Box Office Mojo', url: 'https://boxofficemojo.com/api', type: 'rest', reliability: 0.85 },
      { name: 'The Numbers', url: 'https://the-numbers.com/api', type: 'rest', reliability: 0.8 },
      { name: 'FilmAffinity', url: 'https://api.filmaffinity.com', type: 'rest', reliability: 0.75 },
      { name: 'JustWatch', url: 'https://www.justwatch.com/api', type: 'rest', reliability: 0.8 },
    ],
    series: [
      { name: 'TVmaze', url: 'https://api.tvmaze.com', type: 'rest', reliability: 0.75 },
      { name: 'Trakt', url: 'https://api.trakt.tv', type: 'rest', reliability: 0.75 },
      { name: 'TMDB TV', url: 'https://api.themoviedb.org/3/tv', type: 'rest', reliability: 0.85 },
      { name: 'MyDramaList', url: 'https://mydramalist.com/api', type: 'rest', reliability: 0.8 },
      { name: 'K-Drama Database', url: 'https://kdramalist.com/api', type: 'rest', reliability: 0.75 },
      { name: 'DramaFever', url: 'https://dramafever.com/api', type: 'rest', reliability: 0.7 },
      { name: 'ChineseDrama.info', url: 'https://chinesedrama.info/api', type: 'rest', reliability: 0.7 },
    ],
  },

  rss: {
    news: [
      { name: 'Anime News Network', url: 'https://www.animenewsnetwork.com/all/rss.xml', reliability: 0.85 },
      { name: 'MyAnimeList News', url: 'https://myanimelist.net/rss/news.xml', reliability: 0.8 },
      { name: 'Anime Corner', url: 'https://animecorner.me/feed', reliability: 0.75 },
      { name: 'Crunchyroll News', url: 'https://www.crunchyroll.com/newsrss', reliability: 0.85 },
      { name: 'Anime UK News', url: 'https://animeuknews.net/feed', reliability: 0.75 },
      { name: 'Honey\'s Anime', url: 'https://honeysanime.com/feed', reliability: 0.7 },
      { name: 'Otaku News', url: 'https://otakunews.com/feed', reliability: 0.7 },
      { name: 'Anime Trending', url: 'https://animetrending.com/feed', reliability: 0.7 },
      { name: 'Anime Hunch', url: 'https://animehunch.com/feed', reliability: 0.7 },
      { name: 'The Japan Times', url: 'https://japantimes.co.jp/culture/rss', reliability: 0.85 },
      { name: 'Anime Expo', url: 'https://anime-expo.org/feed', reliability: 0.8 },
      { name: 'Anime Boston', url: 'https://animeboston.com/feed', reliability: 0.75 },
      { name: 'Anime Central', url: 'https://animecentral.com/feed', reliability: 0.75 },
      { name: 'Anime NYC', url: 'https://animenyc.org/feed', reliability: 0.75 },
      { name: 'Tokyo Otaku Mode', url: 'https://otakumode.com/news/rss', reliability: 0.7 },
      { name: 'AnimeBlog', url: 'https://animeblog.rss.hangar-13.com', reliability: 0.6 },
      { name: 'Anime常数', url: 'https://anime常数.com/feed', reliability: 0.6 },
      { name: 'Kaiju Quarterly', url: 'https://kaijuquarterly.com/feed', reliability: 0.7 },
      { name: 'Otaku USA', url: 'https://otakusa.com/rss', reliability: 0.7 },
      { name: 'Anime-Fox', url: 'https://anime-fox.net/feed', reliability: 0.6 },
      { name: 'Anime Dukkan', url: 'https://dukkan.jp/anime/rss', reliability: 0.65 },
      { name: 'Anime Land', url: 'https://anime-land.net/rss', reliability: 0.6 },
      { name: 'Anime News Brasil', url: 'https://animenews.com.br/rss', reliability: 0.7 },
      { name: 'Anime News Italy', url: 'https://animenews.it/rss', reliability: 0.65 },
      { name: 'Anime News France', url: 'https://animenewsfrance.fr/rss', reliability: 0.65 },
      { name: 'Anime News Germany', url: 'https://animenews.de/rss', reliability: 0.65 },
      { name: 'MyAnimeList Editorial', url: 'https://myanimelist.net/editorial/rss', reliability: 0.8 },
      { name: 'AniList Blog', url: 'https://anilist.co/rss', reliability: 0.75 },
      { name: 'Kitsu Blog', url: 'https://kitsu.io/rss', reliability: 0.75 },
      { name: 'Manga Updates', url: 'https://www.mangaupdates.com/rss', reliability: 0.7 },
      { name: 'Anime-Planet Blog', url: 'https://anime-planet.com/rss', reliability: 0.7 },
      { name: 'AniDB News', url: 'https://anidb.net/rss', reliability: 0.75 },
      { name: 'AnimeDB Japan', url: 'https://animedb.jp/rss', reliability: 0.7 },
      { name: 'Japan Foundation', url: 'https://jpf.go.jp/rss', reliability: 0.8 },
      { name: 'Nippon TV', url: 'https://ntv.co.jp/rss', reliability: 0.75 },
      { name: 'TV Tokyo', url: 'https://tv-tokyo.co.jp/rss', reliability: 0.75 },
      { name: 'Anime Awards', url: 'https://animeawards.com/rss', reliability: 0.7 },
      { name: 'Anime conventions calendar', url: 'https://animeconventions.com/rss', reliability: 0.65 },
      { name: 'Anime Music Awards', url: 'https://animamusicawards.com/rss', reliability: 0.65 },
      { name: 'Crunchyroll Expo', url: 'https://crunchyrollexpo.com/feed', reliability: 0.8 },
      { name: 'Anime Imp Awards', url: 'https://animeimpawards.com/rss', reliability: 0.6 },
      { name: 'Tokyo International Anime Fair', url: 'https://tmaf.jp/rss', reliability: 0.7 },
      { name: 'JASIAS', url: 'https://jasias.org/rss', reliability: 0.65 },
      { name: 'Seiyu Awards', url: 'https://seiyuawards.org/rss', reliability: 0.8 },
      { name: 'Kobe Anime Awards', url: 'https://kobe-anime.jp/rss', reliability: 0.7 },
      { name: 'Anime Film Festival', url: 'https://animefilmfestival.com/rss', reliability: 0.65 },
      { name: 'Tokyo Anime Film Festival', url: 'https://tokyoanimefest.jp/rss', reliability: 0.7 },
      { name: 'Japan Media Arts Festival', url: 'https://j-mediaarts.jp/rss', reliability: 0.85 },
      { name: 'Anime Business', url: 'https://animebusiness.com/rss', reliability: 0.7 },
      { name: 'Anime Industry News', url: 'https://animeindustrynews.com/rss', reliability: 0.7 },
      { name: 'Anime Economy', url: 'https://animeconomy.com/rss', reliability: 0.65 },
      { name: 'Manga Toru', url: 'https://mangatoru.com/rss', reliability: 0.7 },
      { name: 'Manga Time', url: 'https://manga-time.net/rss', reliability: 0.7 },
      { name: 'Comic Alive', url: 'https://comic-alive.jp/rss', reliability: 0.7 },
      { name: 'Comic Beam', url: 'https://comic-beam.jp/rss', reliability: 0.7 },
      { name: 'Comic Days', url: 'https://comic-days.jp/rss', reliability: 0.7 },
      { name: 'Young Jump', url: 'https://youngjump.jp/rss', reliability: 0.7 },
      { name: 'Weekly Shōnen Jump', url: 'https://shonenjump.com/rss', reliability: 0.85 },
      { name: 'Weekly Shōnen Magazine', url: 'https://shonenmagazine.com/rss', reliability: 0.8 },
      { name: 'Weekly Shōnen Sirius', url: 'https://shonensirius.jp/rss', reliability: 0.75 },
      { name: 'Monthly Shōnen Gangan', url: 'https://shonengangan.jp/rss', reliability: 0.8 },
      { name: 'Monthly Shōnen Ace', url: 'https://shonen-ace.jp/rss', reliability: 0.75 },
      { name: 'Shōnen Jump+', url: 'https://shonenjumpplus.com/rss', reliability: 0.8 },
      { name: 'Manga Plus', url: 'https://mangaplus.shueisha.co.jp/rss', reliability: 0.8 },
      { name: 'Comico', url: 'https://comico.jp/rss', reliability: 0.75 },
      { name: 'Yonkoma', url: 'https://yonkoma.jp/rss', reliability: 0.65 },
      { name: 'Dengeki Daioh', url: 'https://dengekidaioh.jp/rss', reliability: 0.8 },
      { name: 'Dengeki Moeoh', url: 'https://dengekimoeoh.jp/rss', reliability: 0.7 },
      { name: 'Dragon Magazine', url: 'https://dragon-magazine.jp/rss', reliability: 0.75 },
      { name: 'Famitsu', url: 'https://famitsu.com/rss', reliability: 0.8 },
      { name: '4Gamer', url: 'https://4gamer.net/rss', reliability: 0.75 },
      { name: 'Anime! Anime!', url: 'https://animeanime.jp/rss', reliability: 0.7 },
      { name: 'Akita Shoten', url: 'https://akita-shoten.co.jp/rss', reliability: 0.7 },
      { name: 'Shueisha', url: 'https://shueisha.co.jp/rss', reliability: 0.85 },
      { name: 'Kodansha', url: 'https://kodansha.co.jp/rss', reliability: 0.8 },
      { name: 'Shogakukan', url: 'https://shogakukan.co.jp/rss', reliability: 0.8 },
      { name: 'Hakusensha', url: 'https://haku-sensha.co.jp/rss', reliability: 0.75 },
    ],
    manga: [
      { name: 'Manga Bookshelf', url: 'https://mangabookshelf.com/feed', reliability: 0.7 },
      { name: 'Comic Book Resources', url: 'https://cbr.com/manga/feed', reliability: 0.75 },
      { name: 'Manga Reviews', url: 'https://mangareviews.com/rss', reliability: 0.65 },
      { name: 'Manga News', url: 'https://manganews.com/rss', reliability: 0.65 },
      { name: 'Manga World', url: 'https://mangaworld.com/rss', reliability: 0.65 },
      { name: 'Manga News Japan', url: 'https://manganewsjapan.com/rss', reliability: 0.7 },
      { name: 'Manga Pulse', url: 'https://mangapulse.net/rss', reliability: 0.6 },
      { name: 'Manga Frenzy', url: 'https://mangafrenzy.com/rss', reliability: 0.6 },
      { name: 'Manga Updates', url: 'https://mangaupdates.com/rss', reliability: 0.7 },
      { name: 'Manga Scout', url: 'https://mangascout.com/rss', reliability: 0.6 },
      { name: 'One Piece Updates', url: 'https://onepieceupdates.com/rss', reliability: 0.7 },
      { name: 'Naruto Forums', url: 'https://narutoforums.org/rss', reliability: 0.65 },
      { name: 'BLEACH Forums', url: 'https://bleachforums.com/rss', reliability: 0.65 },
      { name: 'Manga Discussion', url: 'https://mangadiscussion.com/rss', reliability: 0.6 },
      { name: 'Manga Reddit', url: 'https://reddit.com/r/manga.rss', reliability: 0.6 },
    ],
    community: [
      { name: 'Reddit r/anime', url: 'https://reddit.com/r/anime.rss', reliability: 0.5 },
      { name: 'Reddit r/manga', url: 'https://reddit.com/r/manga.rss', reliability: 0.5 },
      { name: 'Reddit r/animemes', url: 'https://reddit.com/r/animemes.rss', reliability: 0.4 },
      { name: 'Reddit r/AnimeSuggest', url: 'https://reddit.com/r/AnimeSuggest.rss', reliability: 0.5 },
      { name: 'Reddit r/anime_irl', url: 'https://reddit.com/r/anime_irl.rss', reliability: 0.4 },
      { name: 'Reddit r/Shitpost', url: 'https://reddit.com/r/AnimeShitpost.rss', reliability: 0.4 },
      { name: 'Reddit r/OnePiece', url: 'https://reddit.com/r/OnePiece.rss', reliability: 0.5 },
      { name: 'Reddit r/Naruto', url: 'https://reddit.com/r/Naruto.rss', reliability: 0.5 },
      { name: 'Reddit r/JujutsuKaisen', url: 'https://reddit.com/r/JujutsuKaisen.rss', reliability: 0.5 },
      { name: 'Reddit r/DemonSlayer', url: 'https://reddit.com/r/DemonSlayer.rss', reliability: 0.5 },
      { name: 'Reddit r/AttackOnTitan', url: 'https://reddit.com/r/AttackOnTitan.rss', reliability: 0.5 },
      { name: 'Reddit r/bleach', url: 'https://reddit.com/r/bleach.rss', reliability: 0.5 },
      { name: 'Reddit r/DragonBall', url: 'https://reddit.com/r/DragonBall.rss', reliability: 0.5 },
      { name: 'Reddit r/MyHeroAcademia', url: 'https://reddit.com/r/MyHeroAcademia.rss', reliability: 0.5 },
      { name: 'Reddit r/BlackClover', url: 'https://reddit.com/r/BlackClover.rss', reliability: 0.5 },
      { name: 'Reddit r/JoJo', url: 'https://reddit.com/r/JoJo.rss', reliability: 0.5 },
      { name: 'Reddit r/HunterXHunter', url: 'https://reddit.com/r/HunterXHunter.rss', reliability: 0.5 },
      { name: 'Reddit r/OnePunchMan', url: 'https://reddit.com/r/OnePunchMan.rss', reliability: 0.5 },
      { name: 'Reddit r/SpyxFamily', url: 'https://reddit.com/r/SpyxFamily.rss', reliability: 0.5 },
      { name: 'Reddit r/ChainsawMan', url: 'https://reddit.com/r/ChainsawMan.rss', reliability: 0.5 },
      { name: 'Reddit r/TokyoRevengers', url: 'https://reddit.com/r/TokyoRevengers.rss', reliability: 0.5 },
      { name: 'Reddit r/SwordArtOnline', url: 'https://reddit.com/r/SwordArtOnline.rss', reliability: 0.5 },
      { name: 'Reddit r/Re Zero', url: 'https://reddit.com/r/Re_Zero.rss', reliability: 0.5 },
      { name: 'Reddit r/Overlord', url: 'https://reddit.com/r/overlord.rss', reliability: 0.5 },
      { name: 'Reddit r/KonoSuba', url: 'https://reddit.com/r/KonoSuba.rss', reliability: 0.5 },
      { name: 'Reddit r/isekai', url: 'https://reddit.com/r/isekai.rss', reliability: 0.5 },
      { name: 'Reddit r/shoujo', url: 'https://reddit.com/r/shoujo.rss', reliability: 0.5 },
      { name: 'Reddit r/ seinen', url: 'https://reddit.com/r/seinen.rss', reliability: 0.5 },
      { name: 'Reddit r/josei', url: 'https://reddit.com/r/josei.rss', reliability: 0.5 },
      { name: 'Reddit r/kdrama', url: 'https://reddit.com/r/kdrama.rss', reliability: 0.5 },
      { name: 'Reddit r/cdramas', url: 'https://reddit.com/r/cdramas.rss', reliability: 0.5 },
      { name: 'Reddit r/asiandrama', url: 'https://reddit.com/r/asiandrama.rss', reliability: 0.5 },
      { name: 'MyAnimeList Forums', url: 'https://myanimelist.net/forum/rss', reliability: 0.5 },
      { name: 'AniList Forums', url: 'https://anilist.co/forum/rss', reliability: 0.5 },
    ],
  },

  sites: {
    news: [
      { name: 'Anime News Network', url: 'https://www.animenewsnetwork.com', reliability: 0.85 },
      { name: 'MyAnimeList', url: 'https://myanimelist.net', reliability: 0.85 },
      { name: 'Anime Corner', url: 'https://animecorner.me', reliability: 0.75 },
      { name: 'Crunchyroll News', url: 'https://www.crunchyroll.com/news', reliability: 0.85 },
      { name: 'Anime Hunch', url: 'https://animehunch.com', reliability: 0.7 },
      { name: 'Otaku News', url: 'https://otakunews.com', reliability: 0.7 },
      { name: 'Anime Trending', url: 'https://animetrending.com', reliability: 0.7 },
      { name: 'Anime UK News', url: 'https://animeuknews.net', reliability: 0.75 },
      { name: 'Honey\'s Anime', url: 'https://honeysanime.com', reliability: 0.7 },
      { name: 'The Japan Times', url: 'https://japantimes.co.jp', reliability: 0.85 },
      { name: 'Nikkei Anime', url: 'https://nikkei.com/anime', reliability: 0.8 },
      { name: 'Yahoo! Anime News', url: 'https://news.yahoo.co.jp/anime', reliability: 0.75 },
      { name: 'Anime Expo', url: 'https://anime-expo.org', reliability: 0.8 },
      { name: 'Anime Boston', url: 'https://animeboston.com', reliability: 0.75 },
      { name: 'Anime Central', url: 'https://animecentral.com', reliability: 0.75 },
      { name: 'Anime NYC', url: 'https://animenyc.org', reliability: 0.75 },
      { name: 'Otaku USA', url: 'https://otakusa.com', reliability: 0.7 },
      { name: 'Anime-Fox', url: 'https://anime-fox.net', reliability: 0.6 },
      { name: 'Anime常数', url: 'https://anime常数.com', reliability: 0.6 },
      { name: 'Kaiju Quarterly', url: 'https://kaijuquarterly.com', reliability: 0.7 },
      { name: 'Otaku Mode', url: 'https://otakumode.com', reliability: 0.7 },
      { name: 'Japan Forward', url: 'https://japanforward.com', reliability: 0.75 },
      { name: 'The Mainichi', url: 'https://mainichi.jp/anime', reliability: 0.75 },
      { name: 'Asahi Shimbun', url: 'https://asahi.com/anime', reliability: 0.75 },
      { name: 'Yomiuri Shimbun', url: 'https://yomiuri.co.jp/anime', reliability: 0.75 },
      { name: 'Nihon Keizai Shimbun', url: 'https://nikkei.com/anime', reliability: 0.8 },
      { name: 'Tokyo Shimbun', url: 'https://tokyo-np.co.jp/anime', reliability: 0.7 },
      { name: 'Animeblog', url: 'https://animeblog.com', reliability: 0.6 },
      { name: 'Anime Raptor', url: 'https://animerap tor.com', reliability: 0.6 },
      { name: 'Anime Obsessive', url: 'https://animeobsessive.com', reliability: 0.65 },
      { name: 'Anime Feminist', url: 'https://animefeminist.com', reliability: 0.65 },
      { name: 'Anime News Brasil', url: 'https://animenews.com.br', reliability: 0.7 },
      { name: 'Anime News Italy', url: 'https://animenews.it', reliability: 0.65 },
      { name: 'Anime News France', url: 'https://animenewsfrance.fr', reliability: 0.65 },
      { name: 'Anime News Germany', url: 'https://animenews.de', reliability: 0.65 },
      { name: 'Anime News Spain', url: 'https://animenews.es', reliability: 0.65 },
      { name: 'Manga Updates', url: 'https://www.mangaupdates.com', reliability: 0.75 },
      { name: 'Anime-Planet', url: 'https://anime-planet.com', reliability: 0.8 },
    ],
    databases: [
      { name: 'MyAnimeList', url: 'https://myanimelist.net', reliability: 0.85 },
      { name: 'AniList', url: 'https://anilist.co', reliability: 0.85 },
      { name: 'Kitsu', url: 'https://kitsu.io', reliability: 0.85 },
      { name: 'Anime-Planet', url: 'https://anime-planet.com', reliability: 0.8 },
      { name: 'AniDB', url: 'https://anidb.net', reliability: 0.85 },
      { name: 'Shikimori', url: 'https://shikimori.one', reliability: 0.8 },
      { name: 'notify.moe', url: 'https://notify.moe', reliability: 0.75 },
      { name: 'Anime News Network Database', url: 'https://www.animenewsnetwork.com/encyclopedia', reliability: 0.85 },
      { name: 'The Movie Database', url: 'https://www.themoviedb.org', reliability: 0.85 },
      { name: 'TVmaze', url: 'https://www.tvmaze.com', reliability: 0.75 },
      { name: 'Trakt', url: 'https://trakt.tv', reliability: 0.75 },
      { name: 'IMDb', url: 'https://www.imdb.com', reliability: 0.9 },
      { name: 'Rotten Tomatoes', url: 'https://www.rottentomatoes.com', reliability: 0.85 },
      { name: 'Letterboxd', url: 'https://letterboxd.com', reliability: 0.8 },
      { name: 'SIMKL', url: 'https://simkl.com', reliability: 0.75 },
    ],
    manhwa: [
      { name: 'WEBTOONS', url: 'https://www.webtoons.com', reliability: 0.85 },
      { name: 'Naver Webtoon', url: 'https://comic.naver.com', reliability: 0.85 },
      { name: 'Kakao Page', url: 'https://page.kakao.com', reliability: 0.85 },
      { name: 'Kakao Webtoon', url: 'https://webtoon.kakao.com', reliability: 0.8 },
      { name: 'Manta', url: 'https://manta.net', reliability: 0.75 },
      { name: 'Lezhin', url: 'https://www.lezhin.com', reliability: 0.7 },
      { name: 'Tapas', url: 'https://tapas.io', reliability: 0.75 },
      { name: 'Tappytoon', url: 'https://tappytoon.com', reliability: 0.7 },
      { name: 'Toomics', url: 'https://toomics.com', reliability: 0.7 },
      { name: 'MrBlue', url: 'https://mrblue.com', reliability: 0.7 },
      { name: 'Bomtoon', url: 'https://bomtoon.com', reliability: 0.7 },
      { name: 'Pocket Comics', url: 'https://pocketcomics.com', reliability: 0.7 },
      { name: 'Naver Series', url: 'https://series.naver.com', reliability: 0.75 },
      { name: 'Kakao Story', url: 'https://story.kakao.com', reliability: 0.7 },
    ],
    liveAction: [
      { name: 'MyDramaList', url: 'https://mydramalist.com', reliability: 0.8 },
      { name: 'K-Drama Database', url: 'https://kdramalist.com', reliability: 0.8 },
      { name: 'DramaFever', url: 'https://dramafever.com', reliability: 0.7 },
      { name: 'ChineseDrama.info', url: 'https://chinesedrama.info', reliability: 0.7 },
      { name: 'DramaNice', url: 'https://dramasnice.com', reliability: 0.65 },
      { name: 'AsianWiki', url: 'https://asianwiki.com', reliability: 0.75 },
      { name: 'Dramalist', url: 'https://dramalist.com', reliability: 0.7 },
      { name: 'Viki', url: 'https://www.viki.com', reliability: 0.8 },
      { name: 'Viu', url: 'https://www.viu.com', reliability: 0.75 },
    ],
    film: [
      { name: 'IMDb', url: 'https://www.imdb.com', reliability: 0.9 },
      { name: 'The Movie Database', url: 'https://www.themoviedb.org', reliability: 0.85 },
      { name: 'Rotten Tomatoes', url: 'https://www.rottentomatoes.com', reliability: 0.85 },
      { name: 'Letterboxd', url: 'https://letterboxd.com', reliability: 0.8 },
      { name: 'Box Office Mojo', url: 'https://boxofficemojo.com', reliability: 0.85 },
      { name: 'The Numbers', url: 'https://the-numbers.com', reliability: 0.8 },
      { name: 'FilmAffinity', url: 'https://www.filmaffinity.com', reliability: 0.75 },
      { name: 'Metacritic', url: 'https://www.metacritic.com', reliability: 0.8 },
      { name: 'CinemaScore', url: 'https://www.cinemascore.com', reliability: 0.8 },
    ],
  },

  social: {
    twitter: [
      { name: '@anime_chiikawa', handle: 'anime_chiikawa', reliability: 0.7 },
      { name: '@DB_anime_info', handle: 'DB_anime_info', reliability: 0.75 },
      { name: '@AnimeCorner', handle: 'AnimeCornerNews', reliability: 0.75 },
      { name: '@Crunchyroll', handle: 'Crunchyroll', reliability: 0.85 },
      { name: '@SugoiLITE', handle: 'SugoiLITE', reliability: 0.7 },
      { name: '@MangaMoguraRE', handle: 'MangaMoguraRE', reliability: 0.7 },
      { name: '@WorstGen', handle: 'WorstGen', reliability: 0.65 },
      { name: '@animenews', handle: 'animenews', reliability: 0.8 },
      { name: '@Anime_News_eng', handle: 'Anime_News_eng', reliability: 0.75 },
      { name: '@animenewsnetwork', handle: 'animenewsnetwork', reliability: 0.85 },
      { name: '@MyAnimeList', handle: 'MyAnimeList', reliability: 0.85 },
      { name: '@Kitsu', handle: 'kitsu', reliability: 0.8 },
      { name: '@AniListCo', handle: 'AniListCo', reliability: 0.8 },
      { name: '@AnimeExpo', handle: 'AnimeExpo', reliability: 0.85 },
      { name: '@AnimeCentral', handle: 'AnimeCentral', reliability: 0.75 },
      { name: '@AnimeBoston', handle: 'AnimeBoston', reliability: 0.75 },
      { name: '@AnimeNYC', handle: 'AnimeNYC', reliability: 0.75 },
      { name: '@SeiyuAwards', handle: 'SeiyuAwards', reliability: 0.85 },
      { name: '@Shueisha', handle: 'Shueisha', reliability: 0.85 },
      { name: '@shueisha_PR', handle: 'shueisha_PR', reliability: 0.8 },
      { name: '@kodansha_us', handle: 'kodansha_us', reliability: 0.8 },
      { name: '@vizmedia', handle: 'vizmedia', reliability: 0.85 },
      { name: '@YenPress', handle: 'YenPress', reliability: 0.8 },
      { name: '@SevenSeasUSA', handle: 'SevenSeasUSA', reliability: 0.8 },
      { name: '@KodanshaUSA', handle: 'KodanshaUSA', reliability: 0.8 },
      { name: '@Vertical', handle: 'Vertical', reliability: 0.8 },
      { name: '@AnimeDuke', handle: 'AnimeDuke', reliability: 0.65 },
      { name: '@AnimeDoge', handle: 'AnimeDoge', reliability: 0.6 },
      { name: '@AnimeLounge', handle: 'AnimeLounge', reliability: 0.6 },
      { name: '@AnimePics', handle: 'AnimePics', reliability: 0.5 },
      { name: '@AnimeDekku', handle: 'AnimeDekku', reliability: 0.6 },
      { name: '@AnimeMeme', handle: 'AnimeMeme', reliability: 0.5 },
      { name: '@animenewsfrance', handle: 'animenewsfrance', reliability: 0.7 },
      { name: '@AnimeNewsBR', handle: 'AnimeNewsBR', reliability: 0.7 },
      { name: '@animenewsde', handle: 'animenewsde', reliability: 0.7 },
      { name: '@animenewsit', handle: 'animenewsit', reliability: 0.7 },
      { name: '@animenews_es', handle: 'animenews_es', reliability: 0.7 },
      { name: '@ONE_PIECE_anime', handle: 'ONE_PIECE_anime', reliability: 0.75 },
      { name: '@naruto_club', handle: 'naruto_club', reliability: 0.65 },
      { name: '@JujutsuKaisen', handle: 'JujutsuKaisen', reliability: 0.8 },
      { name: '@DemonSlayer_en', handle: 'DemonSlayer_en', reliability: 0.8 },
      { name: '@attackontitan', handle: 'attackontitan', reliability: 0.75 },
      { name: '@OP_Official_Anime', handle: 'OP_Official_Anime', reliability: 0.8 },
      { name: '@OnePieceDice', handle: 'OnePieceDice', reliability: 0.6 },
      { name: '@OnePieceNews', handle: 'OnePieceNews', reliability: 0.65 },
      { name: '@OnePieceUpdates', handle: 'OnePieceUpdates', reliability: 0.65 },
      { name: '@MangaUpdates', handle: 'MangaUpdates', reliability: 0.75 },
      { name: '@AnimeUpdates', handle: 'AnimeUpdates', reliability: 0.65 },
      { name: '@MangaReviewers', handle: 'MangaReviewers', reliability: 0.6 },
      { name: '@AnimeScoop', handle: 'AnimeScoop', reliability: 0.65 },
      { name: '@AnimeHype', handle: 'AnimeHype', reliability: 0.65 },
      { name: '@AnimeForLife', handle: 'AnimeForLife', reliability: 0.5 },
      { name: '@NotAnimeFan', handle: 'NotAnimeFan', reliability: 0.5 },
      { name: '@AnimeIsLife', handle: 'AnimeIsLife', reliability: 0.5 },
      { name: '@BestAnimeFeeds', handle: 'BestAnimeFeeds', reliability: 0.6 },
      { name: '@AnimeOnlyFans', handle: 'AnimeOnlyFans', reliability: 0.5 },
      { name: '@AnimeAddicts', handle: 'AnimeAddicts', reliability: 0.6 },
      { name: '@AnimeCore', handle: 'AnimeCore', reliability: 0.5 },
      { name: '@OtakuCulture', handle: 'OtakuCulture', reliability: 0.6 },
      { name: '@OtakuNews', handle: 'OtakuNews', reliability: 0.7 },
      { name: '@OtakuLife', handle: 'OtakuLife', reliability: 0.5 },
      { name: '@AnimeOtaku', handle: 'AnimeOtaku', reliability: 0.5 },
      { name: '@MangaLovers', handle: 'MangaLovers', reliability: 0.6 },
      { name: '@MangaAddicts', handle: 'MangaAddicts', reliability: 0.6 },
      { name: '@MangaDaily', handle: 'MangaDaily', reliability: 0.6 },
      { name: '@ManhwaUpdates', handle: 'ManhwaUpdates', reliability: 0.65 },
      { name: '@WebtoonUpdates', handle: 'WebtoonUpdates', reliability: 0.65 },
      { name: '@ManhwaAddicts', handle: 'ManhwaAddicts', reliability: 0.6 },
      { name: '@AnimeAwards', handle: 'AnimeAwards', reliability: 0.75 },
      { name: '@CrunchyrollAwards', handle: 'CrunchyrollAwards', reliability: 0.8 },
    ],
    reddit: [
      { name: 'r/anime', url: 'https://reddit.com/r/anime', reliability: 0.5 },
      { name: 'r/manga', url: 'https://reddit.com/r/manga', reliability: 0.5 },
      { name: 'r/manhwa', url: 'https://reddit.com/r/manhwa', reliability: 0.5 },
      { name: 'r/isekai', url: 'https://reddit.com/r/isekai', reliability: 0.5 },
      { name: 'r/Animeanime', url: 'https://reddit.com/r/Animeanime', reliability: 0.45 },
      { name: 'r/AnimeSuggest', url: 'https://reddit.com/r/AnimeSuggest', reliability: 0.5 },
      { name: 'r/animemes', url: 'https://reddit.com/r/animemes', reliability: 0.4 },
      { name: 'r/AnimeCircles', url: 'https://reddit.com/r/AnimeCircles', reliability: 0.45 },
      { name: 'r/anime_irl', url: 'https://reddit.com/r/anime_irl', reliability: 0.4 },
      { name: 'r/Shitpost', url: 'https://reddit.com/r/AnimeShitpost', reliability: 0.4 },
      { name: 'r/AnimeWallpaper', url: 'https://reddit.com/r/AnimeWallpaper', reliability: 0.5 },
      { name: 'r/AnimeID', url: 'https://reddit.com/r/AnimeID', reliability: 0.5 },
      { name: 'r/AnimeMusic', url: 'https://reddit.com/r/AnimeMusic', reliability: 0.5 },
      { name: 'r/AnimeFigures', url: 'https://reddit.com/r/AnimeFigures', reliability: 0.5 },
      { name: 'r/AnimeSketch', url: 'https://reddit.com/r/AnimeSketch', reliability: 0.5 },
      { name: 'r/OnePiece', url: 'https://reddit.com/r/OnePiece', reliability: 0.5 },
      { name: 'r/Naruto', url: 'https://reddit.com/r/Naruto', reliability: 0.5 },
      { name: 'r/JujutsuKaisen', url: 'https://reddit.com/r/JujutsuKaisen', reliability: 0.5 },
      { name: 'r/DemonSlayer', url: 'https://reddit.com/r/DemonSlayer', reliability: 0.5 },
      { name: 'r/AttackOnTitan', url: 'https://reddit.com/r/AttackOnTitan', reliability: 0.5 },
      { name: 'r/bleach', url: 'https://reddit.com/r/bleach', reliability: 0.5 },
      { name: 'r/DragonBall', url: 'https://reddit.com/r/DragonBall', reliability: 0.5 },
      { name: 'r/MyHeroAcademia', url: 'https://reddit.com/r/MyHeroAcademia', reliability: 0.5 },
      { name: 'r/BlackClover', url: 'https://reddit.com/r/BlackClover', reliability: 0.5 },
      { name: 'r/JoJo', url: 'https://reddit.com/r/JoJo', reliability: 0.5 },
      { name: 'r/HunterXHunter', url: 'https://reddit.com/r/HunterXHunter', reliability: 0.5 },
      { name: 'r/OnePunchMan', url: 'https://reddit.com/r/OnePunchMan', reliability: 0.5 },
      { name: 'r/SpyxFamily', url: 'https://reddit.com/r/SpyxFamily', reliability: 0.5 },
      { name: 'r/ChainsawMan', url: 'https://reddit.com/r/ChainsawMan', reliability: 0.5 },
      { name: 'r/TokyoRevengers', url: 'https://reddit.com/r/TokyoRevengers', reliability: 0.5 },
      { name: 'r/SwordArtOnline', url: 'https://reddit.com/r/SwordArtOnline', reliability: 0.5 },
      { name: 'r/Re_Zero', url: 'https://reddit.com/r/Re_Zero', reliability: 0.5 },
      { name: 'r/overlord', url: 'https://reddit.com/r/overlord', reliability: 0.5 },
      { name: 'r/KonoSuba', url: 'https://reddit.com/r/KonoSuba', reliability: 0.5 },
      { name: 'r/shoujo', url: 'https://reddit.com/r/shoujo', reliability: 0.5 },
      { name: 'r/seinen', url: 'https://reddit.com/r/seinen', reliability: 0.5 },
      { name: 'r/josei', url: 'https://reddit.com/r/josei', reliability: 0.5 },
      { name: 'r/kdrama', url: 'https://reddit.com/r/kdrama', reliability: 0.5 },
      { name: 'r/cdramas', url: 'https://reddit.com/r/cdramas', reliability: 0.5 },
      { name: 'r/asiandrama', url: 'https://reddit.com/r/asiandrama', reliability: 0.5 },
      { name: 'r/MangaCollectors', url: 'https://reddit.com/r/MangaCollectors', reliability: 0.5 },
      { name: 'r/AnimeDeals', url: 'https://reddit.com/r/AnimeDeals', reliability: 0.5 },
      { name: 'r/AnimeDeals', url: 'https://reddit.com/r/AnimeDeals', reliability: 0.5 },
    ],
    discord: [
      { name: 'One Piece Spoilers', invite: 'onepiecespoilers', reliability: 0.5 },
      { name: 'Shonen Paradise', invite: 'shonenparadise', reliability: 0.55 },
      { name: 'Anime Hub', invite: 'animehub', reliability: 0.5 },
      { name: 'Manga Readers', invite: 'mangareaders', reliability: 0.5 },
      { name: 'Otaku Community', invite: 'otakucommunity', reliability: 0.5 },
      { name: 'Anime Discussions', invite: 'animediscussions', reliability: 0.5 },
      { name: 'K-Drama Fan Club', invite: 'kdramafanclub', reliability: 0.5 },
      { name: 'Manhwa Club', invite: 'manhwaclub', reliability: 0.5 },
      { name: 'Anime Awards Server', invite: 'animeawards', reliability: 0.55 },
      { name: 'Crunchyroll Community', invite: 'crunchyroll', reliability: 0.6 },
    ],
    youtube: [
      { name: 'Gigguk', url: 'https://youtube.com/c/Gigguk', reliability: 0.7 },
      { name: 'Mother\'s Basement', url: 'https://youtube.com/c/MothersBasement', reliability: 0.7 },
      { name: 'The Anime Man', url: 'https://youtube.com/c/TheAnimeMan', reliability: 0.7 },
      { name: 'Crunchyroll', url: 'https://youtube.com/c/Crunchyroll', reliability: 0.85 },
      { name: 'Muse Asia', url: 'https://youtube.com/c/MuseAsia', reliability: 0.75 },
      { name: 'Ani-One', url: 'https://youtube.com/c/AniOne', reliability: 0.75 },
      { name: 'Animax', url: 'https://youtube.com/c/Animax', reliability: 0.75 },
      { name: 'Funimation', url: 'https://youtube.com/c/Funimation', reliability: 0.85 },
      { name: 'Sentai Filmworks', url: 'https://youtube.com/c/SentaiFilmworks', reliability: 0.8 },
      { name: 'Anime Lucy', url: 'https://youtube.com/c/AnimeLucy', reliability: 0.6 },
      { name: 'Rice Digital', url: 'https://youtube.com/c/RiceDigital', reliability: 0.65 },
      { name: 'Nerdist Anime', url: 'https://youtube.com/c/NerdistAnime', reliability: 0.7 },
      { name: 'GameSpot Anime', url: 'https://youtube.com/c/GameSpotAnime', reliability: 0.7 },
      { name: 'IGN Anime', url: 'https://youtube.com/c/IGNAnime', reliability: 0.7 },
      { name: 'Polygon Anime', url: 'https://youtube.com/c/PolygonAnime', reliability: 0.7 },
      { name: 'Anime Maru', url: 'https://youtube.com/c/AnimeMaru', reliability: 0.65 },
      { name: 'Sakura Girl', url: 'https://youtube.com/c/SakuraGirl', reliability: 0.6 },
      { name: 'Manga Reviewer', url: 'https://youtube.com/c/MangaReviewer', reliability: 0.6 },
      { name: 'Anime Theory', url: 'https://youtube.com/c/AnimeTheory', reliability: 0.65 },
      { name: 'Ranton', url: 'https://youtube.com/c/Ranton', reliability: 0.6 },
      { name: 'CDawgVA', url: 'https://youtube.com/c/CDawgVA', reliability: 0.65 },
      { name: 'JoJo\'s Bizarre Adventure', url: 'https://youtube.com/c/JoJoAnime', reliability: 0.7 },
      { name: 'Team Four Star', url: 'https://youtube.com/c/TeamFourStar', reliability: 0.6 },
      { name: 'Nux Taku', url: 'https://youtube.com/c/NuxTaku', reliability: 0.55 },
      { name: 'Glass Reflection', url: 'https://youtube.com/c/GlassReflection', reliability: 0.6 },
      { name: 'Rasmus Lilliedahl', url: 'https://youtube.com/c/RasmusLilliedahl', reliability: 0.6 },
      { name: 'R瞻', url: 'https://youtube.com/c/AnimeR瞻', reliability: 0.5 },
      { name: 'Canipa育', url: 'https://youtube.com/c/CanipaMain', reliability: 0.6 },
      { name: 'Sukanime', url: 'https://youtube.com/c/Sukanime', reliability: 0.55 },
      { name: 'Rik基', url: 'https://youtube.com/c/Rikku', reliability: 0.5 },
      { name: 'FrenchAnimeFries', url: 'https://youtube.com/c/FrenchAnimeFries', reliability: 0.55 },
      { name: 'Riyaz', url: 'https://youtube.com/c/RiyazAnime', reliability: 0.5 },
      { name: 'Askolan', url: 'https://youtube.com/c/Askolan', reliability: 0.5 },
      { name: 'The Anime Podcast', url: 'https://youtube.com/c/TheAnimePodcast', reliability: 0.6 },
      { name: 'Anime Addicts', url: 'https://youtube.com/c/AnimeAddicts', reliability: 0.6 },
      { name: 'Anime Cafe', url: 'https://youtube.com/c/AnimeCafe', reliability: 0.55 },
      { name: 'Anime History', url: 'https://youtube.com/c/AnimeHistory', reliability: 0.65 },
      { name: 'Anime Explained', url: 'https://youtube.com/c/AnimeExplained', reliability: 0.65 },
      { name: 'Anime Universe', url: 'https://youtube.com/c/AnimeUniverse', reliability: 0.55 },
      { name: 'Anime Review Show', url: 'https://youtube.com/c/AnimeReviewShow', reliability: 0.5 },
      { name: 'Anime Weekly', url: 'https://youtube.com/c/AnimeWeekly', reliability: 0.6 },
      { name: 'Anime News Network', url: 'https://youtube.com/c/AnimeNewsNetwork', reliability: 0.8 },
      { name: 'MyAnimeList', url: 'https://youtube.com/c/MyAnimeList', reliability: 0.8 },
      { name: 'AniList', url: 'https://youtube.com/c/AniList', reliability: 0.75 },
      { name: 'Kitsu', url: 'https://youtube.com/c/Kitsu', reliability: 0.75 },
      { name: 'Anime-Planet', url: 'https://youtube.com/c/AnimePlanet', reliability: 0.75 },
      { name: 'Animedia', url: 'https://youtube.com/c/Animedia', reliability: 0.6 },
      { name: 'Anime Academy', url: 'https://youtube.com/c/AnimeAcademy', reliability: 0.6 },
      { name: 'Anime Insight', url: 'https://youtube.com/c/AnimeInsight', reliability: 0.65 },
      { name: 'Anime Style', url: 'https://youtube.com/c/AnimeStyle', reliability: 0.65 },
      { name: 'Anime Studies', url: 'https://youtube.com/c/AnimeStudies', reliability: 0.6 },
      { name: 'Anime Nippon', url: 'https://youtube.com/c/AnimeNippon', reliability: 0.6 },
      { name: 'Japanamine', url: 'https://youtube.com/c/Japanamine', reliability: 0.6 },
      { name: 'Anime Dake', url: 'https://youtube.com/c/AnimeDake', reliability: 0.5 },
      { name: 'Anime Hub', url: 'https://youtube.com/c/AnimeHubOfficial', reliability: 0.5 },
      { name: 'Manga Box', url: 'https://youtube.com/c/MangaBox', reliability: 0.7 },
      { name: 'Manhwa Addicts', url: 'https://youtube.com/c/ManhwaAddicts', reliability: 0.55 },
      { name: 'Webtoon Canvas', url: 'https://youtube.com/c/WebtoonCanvas', reliability: 0.6 },
      { name: 'WEBTOON', url: 'https://youtube.com/c/WEBTOON', reliability: 0.75 },
    ],
  },

  rumors: {
    leaks: [
      { name: 'Anime Leakers', url: 'https://t.me/animeleakers', reliability: 0.3 },
      { name: 'SpoilerAni', url: 'https://t.me/spoilerani', reliability: 0.3 },
      { name: 'Anime Spoilers Hub', url: 'https://t.me/animespoilershub', reliability: 0.3 },
      { name: 'Manga Spoilers', url: 'https://t.me/mangaspoilers', reliability: 0.3 },
      { name: 'One Piece Spoilers', url: 'https://t.me/onepiecespoilers', reliability: 0.35 },
      { name: 'Naruto Spoilers', url: 'https://t.me/narutospoiders', reliability: 0.3 },
      { name: 'JJK Spoilers', url: 'https://t.me/jjkspoilers', reliability: 0.35 },
      { name: 'Demon Slayer Spoilers', url: 'https://t.me/demonslayerspoilers', reliability: 0.35 },
      { name: 'Bleach Spoilers', url: 'https://t.me/bleachspoilers', reliability: 0.3 },
      { name: 'Chainsaw Man Spoilers', url: 'https://t.me/chainsawmanspoilers', reliability: 0.35 },
      { name: 'Spy x Family Spoilers', url: 'https://t.me/spyfamilyspoilers', reliability: 0.35 },
      { name: 'Tokyo Revengers Spoilers', url: 'https://t.me/tokyorevengersspoilers', reliability: 0.35 },
      { name: 'Black Clover Spoilers', url: 'https://t.me/blackcloverspoilers', reliability: 0.3 },
      { name: 'Boruto Spoilers', url: 'https://t.me/borutospoiders', reliability: 0.3 },
      { name: 'Dragon Ball Spoilers', url: 'https://t.me/dbspoilers', reliability: 0.3 },
      { name: 'My Hero Academia Spoilers', url: 'https://t.me/mhaspoilers', reliability: 0.3 },
      { name: 'Hunter x Hunter Spoilers', url: 'https://t.me/hxhspoilers', reliability: 0.3 },
      { name: 'Attack on Titan Spoilers', url: 'https://t.me/aotspoilers', reliability: 0.35 },
      { name: 'JoJo Spoilers', url: 'https://t.me/jojospoilers', reliability: 0.3 },
      { name: 'One Punch Man Spoilers', url: 'https://t.me/opmspoilers', reliability: 0.3 },
      { name: 'Kaguya Sama Spoilers', url: 'https://t.me/kaguspoilers', reliability: 0.3 },
      { name: 'Kanojo Okarishimasu Spoilers', url: 'https://t.me/kanokarispoilers', reliability: 0.3 },
      { name: 'Komi Can\'t Communicate', url: 'https://t.me/komicanotcommunicate', reliability: 0.3 },
      { name: 'Dr. Stone Spoilers', url: 'https://t.me/drstonespoilers', reliability: 0.3 },
      { name: 'Fire Force Spoilers', url: 'https://t.me/fireforcespoilers', reliability: 0.3 },
      { name: 'Mob Psycho 100 Spoilers', url: 'https://t.me/mobpscho100spoilers', reliability: 0.3 },
      { name: 'Vinland Saga Spoilers', url: 'https://t.me/vinlandsagastroilers', reliability: 0.35 },
      { name: 'Frieren Spoilers', url: 'https://t.me/frierenspoilers', reliability: 0.35 },
      { name: 'Sousou no Frieren', url: 'https://t.me/sousoufrieren', reliability: 0.35 },
      { name: 'Oshi no Ko Spoilers', url: 'https://t.me/oshinokospoilers', reliability: 0.35 },
      { name: 'Witch Hat Atelier', url: 'https://t.me/witchhatatelier', reliability: 0.3 },
      { name: 'Kaiju No. 8', url: 'https://t.me/kaijuno8', reliability: 0.35 },
      { name: 'Blue Lock Spoilers', url: 'https://t.me/bluelockspoilers', reliability: 0.35 },
      { name: 'Sakuna', url: 'https://t.me/sakuna', reliability: 0.3 },
      { name: 'Dandadan', url: 'https://t.me/dandadan', reliability: 0.35 },
      { name: 'Killing Stalking', url: 'https://t.me/killingstalking', reliability: 0.3 },
      { name: 'Lore Olympus', url: 'https://t.me/loreolympus', reliability: 0.3 },
      { name: 'True Beauty', url: 'https://t.me/truebeauty', reliability: 0.3 },
      { name: 'Sweet Home', url: 'https://t.me/sweethome', reliability: 0.35 },
      { name: 'Tower of God', url: 'https://t.me/towerofgod', reliability: 0.3 },
      { name: 'Noblesse', url: 'https://t.me/noblesse', reliability: 0.3 },
      { name: 'God of High School', url: 'https://t.me/godofhighschool', reliability: 0.3 },
      { name: 'Tale of the White Snake', url: 'https://t.me/taleofwhitesnake', reliability: 0.3 },
      { name: 'Lookism', url: 'https://t.me/lookism', reliability: 0.3 },
      { name: 'Omniscient Reader', url: 'https://t.me/omniscientreader', reliability: 0.35 },
      { name: 'Solo Leveling', url: 'https://t.me/sololeveling', reliability: 0.35 },
      { name: 'The Beginning After The End', url: 'https://t.me/tbae', reliability: 0.35 },
      { name: 'Eleceed', url: 'https://t.me/eleceed', reliability: 0.3 },
      { name: 'Study Group', url: 'https://t.me/studygroup', reliability: 0.3 },
      { name: 'Legend of the Northern Blade', url: 'https://t.me/lonb', reliability: 0.3 },
      { name: 'Return of the Blonde', url: 'https://t.me/rotb', reliability: 0.3 },
      { name: 'Wind Breaker', url: 'https://t.me/windbreaker', reliability: 0.3 },
      { name: 'Noble Anonymous', url: 'https://t.me/nobleanonymous', reliability: 0.3 },
      { name: 'Gosu', url: 'https://t.me/gosu', reliability: 0.3 },
      { name: 'Murcielago', url: 'https://t.me/murcielago', reliability: 0.3 },
      { name: 'Bastard', url: 'https://t.me/bastard', reliability: 0.3 },
      { name: 'Pigmal', url: 'https://t.me/pigmal', reliability: 0.3 },
      { name: 'Midnight Rain', url: 'https://t.me/midnightrain', reliability: 0.3 },
    ],
    forums: [
      { name: '4chan /a/', url: 'https://boards.4channel.org/a', reliability: 0.25 },
      { name: '4chan /v/', url: 'https://boards.4channel.org/v', reliability: 0.25 },
      { name: '4chan /c/', url: 'https://boards.4channel.org/c', reliability: 0.25 },
      { name: '4chan /m/', url: 'https://boards.4channel.org/m', reliability: 0.3 },
      { name: '4chan /jk/', url: 'https://boards.4channel.org/jk', reliability: 0.25 },
      { name: '4chan /pol/', url: 'https://boards.4channel.org/pol', reliability: 0.2 },
      { name: 'Nexus Forums', url: 'https://forums.nexusl2.com', reliability: 0.3 },
      { name: 'Anime Forums', url: 'https://animeforums.com', reliability: 0.35 },
      { name: 'Manga Forums', url: 'https://mangaforums.org', reliability: 0.35 },
      { name: 'Animenfo', url: 'https://animenfo.com', reliability: 0.3 },
      { name: 'AnimeSuki', url: 'https://animesuki.com', reliability: 0.35 },
      { name: 'MyAnimeList Forums', url: 'https://myanimelist.net/forum', reliability: 0.4 },
      { name: 'AniList Forums', url: 'https://anilist.co/forum', reliability: 0.4 },
      { name: 'Anime Planet Forums', url: 'https://anime-planet.com/forum', reliability: 0.35 },
      { name: 'AnimeSub', url: 'https://animesub.info', reliability: 0.3 },
      { name: 'AnimeHype Forums', url: 'https://animehype.com/forum', reliability: 0.35 },
      { name: 'AnimeChase', url: 'https://animechase.com', reliability: 0.3 },
      { name: 'AnimeByte', url: 'https://animebyte.io', reliability: 0.3 },
      { name: 'AnimeVerse', url: 'https://animeverse.io', reliability: 0.3 },
      { name: 'AnimeZent', url: 'https://animezent.com', reliability: 0.3 },
      { name: 'AnimeArchive', url: 'https://animearchive.org', reliability: 0.3 },
      { name: 'AnimeDream', url: 'https://animedream.io', reliability: 0.3 },
      { name: 'AnimeWorld', url: 'https://animeworld.io', reliability: 0.3 },
      { name: 'AnimeTalk', url: 'https://animetalk.io', reliability: 0.3 },
      { name: 'AnimeBuzz', url: 'https://animebuzz.io', reliability: 0.3 },
      { name: 'AnimeCore', url: 'https://animecore.io', reliability: 0.3 },
      { name: 'AnimeZone', url: 'https://animezone.io', reliability: 0.3 },
      { name: 'AnimeHub', url: 'https://animehub.io', reliability: 0.3 },
      { name: 'AnimeBase', url: 'https://animebase.io', reliability: 0.3 },
      { name: 'AnimeCity', url: 'https://animecity.io', reliability: 0.3 },
      { name: 'AnimeLand', url: 'https://animeland.io', reliability: 0.3 },
      { name: 'AnimeNation', url: 'https://animenation.io', reliability: 0.3 },
      { name: 'AnimeStation', url: 'https://animestation.io', reliability: 0.3 },
      { name: 'AnimeRock', url: 'https://animerock.io', reliability: 0.3 },
      { name: 'AnimeX', url: 'https://animex.io', reliability: 0.3 },
      { name: 'AnimeTime', url: 'https://animetime.io', reliability: 0.3 },
      { name: 'AnimeHD', url: 'https://animehd.io', reliability: 0.3 },
      { name: 'AnimeOnline', url: 'https://animeonline.io', reliability: 0.3 },
      { name: 'AnimeStream', url: 'https://animestream.io', reliability: 0.3 },
      { name: 'AnimeTV', url: 'https://animetv.io', reliability: 0.3 },
    ],
    insiders: [
      { name: 'Anime Leaker', handle: '@animeleaker', reliability: 0.3 },
      { name: 'Manga Insider', handle: '@mangainsider', reliability: 0.3 },
      { name: 'Anime Spoilers', handle: '@animespoiders', reliability: 0.3 },
      { name: 'Anime News Leaker', handle: '@animenewsleaker', reliability: 0.35 },
      { name: 'Industry Insider', handle: '@industryinsider', reliability: 0.35 },
      { name: 'Anime Leaks Hub', handle: '@animeleakshub', reliability: 0.3 },
      { name: 'Manga Spoiler Alert', handle: '@mangaspoileralert', reliability: 0.3 },
      { name: 'One Piece Insider', handle: '@onepieceinsider', reliability: 0.35 },
      { name: 'Naruto Insider', handle: '@narutoinsider', reliability: 0.3 },
      { name: 'JJK Insider', handle: '@jjkinsider', reliability: 0.35 },
      { name: 'Demon Slayer Insider', handle: '@demonslayerinsider', reliability: 0.35 },
      { name: 'Anime Industry News', handle: '@animeindustrynews', reliability: 0.35 },
      { name: 'Anime Leaks 2', handle: '@animeleaks2', reliability: 0.3 },
      { name: 'Manga Leaker', handle: '@mangaleaker', reliability: 0.3 },
      { name: 'Anime Spoiler Channel', handle: '@animespoilerchannel', reliability: 0.3 },
      { name: 'Weekly Shonen Jump Leaks', handle: '@wsjleaks', reliability: 0.35 },
      { name: 'Shueisha Leaks', handle: '@shueialeaks', reliability: 0.35 },
      { name: 'Kodansha Leaks', handle: '@kodanshaieaks', reliability: 0.35 },
      { name: 'Crunchyroll Leaks', handle: '@crunchyrollleaks', reliability: 0.3 },
      { name: 'Funimation Leaks', handle: '@funimationleaks', reliability: 0.3 },
      { name: 'Anime Production Insider', handle: '@animeproduction', reliability: 0.35 },
      { name: 'Studio Insider', handle: '@studioinsider', reliability: 0.35 },
      { name: 'Voice Actor Insider', handle: '@voiceactorinsider', reliability: 0.35 },
      { name: 'Seiyuu News', handle: '@seiyuunews', reliability: 0.35 },
      { name: 'Anime Awards Leaks', handle: '@animeawardsleaks', reliability: 0.3 },
      { name: 'Convention Insider', handle: '@conventioninsider', reliability: 0.35 },
      { name: 'Anime Expo Leaks', handle: '@animeexpoieaks', reliability: 0.35 },
      { name: 'LeakDoge', handle: '@leakdoge', reliability: 0.3 },
      { name: 'Anime Leakz', handle: '@animeleakz', reliability: 0.3 },
      { name: 'Manga Leakz', handle: '@mangaleakz', reliability: 0.3 },
      { name: 'Anime Truth', handle: '@animetruth', reliability: 0.3 },
      { name: 'Anime Facts', handle: '@animefacts', reliability: 0.3 },
      { name: 'Anime Rumors', handle: '@animerumors', reliability: 0.25 },
      { name: 'Manga Rumors', handle: '@mangarumors', reliability: 0.25 },
      { name: 'Anime Whisperer', handle: '@animewhisperer', reliability: 0.3 },
      { name: 'Manga Whisperer', handle: '@mangawhisperer', reliability: 0.3 },
      { name: 'Anime Prophet', handle: '@animeprophet', reliability: 0.25 },
      { name: 'Manga Prophet', handle: '@mangaprophet', reliability: 0.25 },
      { name: 'Anime Oracle', handle: '@animeoracle', reliability: 0.25 },
      { name: 'Manga Oracle', handle: '@mangaoracle', reliability: 0.25 },
      { name: 'Anime Future', handle: '@animefuture', reliability: 0.25 },
      { name: 'Manga Future', handle: '@mangafuture', reliability: 0.25 },
      { name: 'Anime Predictor', handle: '@animepredictor', reliability: 0.25 },
      { name: 'Manga Predictor', handle: '@mangapredictor', reliability: 0.25 },
      { name: 'Anime Seer', handle: '@animeseer', reliability: 0.25 },
      { name: 'Manga Seer', handle: '@mangaseer', reliability: 0.25 },
      { name: 'Anime Visionary', handle: '@animevisionary', reliability: 0.3 },
      { name: 'Manga Visionary', handle: '@mangavisionary', reliability: 0.3 },
    ],
  },

  reliabilityTiers: {
    tier1: { score: 1.0, description: 'Official/Government' },
    tier2: { score: 0.85, description: 'Established Database' },
    tier3: { score: 0.7, description: 'Trusted News' },
    tier4: { score: 0.5, description: 'Community' },
    tier5: { score: 0.3, description: 'Unverified (Rumors)' },
  },
};

export type SourceCategory = keyof typeof SOURCES_DATABASE;
export type ApiCategory = keyof typeof SOURCES_DATABASE.apis;
export type RssCategory = keyof typeof SOURCES_DATABASE.rss;
export type SitesCategory = keyof typeof SOURCES_DATABASE.sites;
export type SocialCategory = keyof typeof SOURCES_DATABASE.social;
export type RumorsCategory = keyof typeof SOURCES_DATABASE.rumors;

export interface Source {
  name: string;
  url?: string;
  type?: string;
  reliability: number;
  handle?: string;
  invite?: string;
}

export interface ReliabilityTier {
  score: number;
  description: string;
}

export function getReliabilityTier(reliability: number): string {
  if (reliability >= 0.85) return 'tier1';
  if (reliability >= 0.7) return 'tier2';
  if (reliability >= 0.5) return 'tier3';
  if (reliability >= 0.3) return 'tier4';
  return 'tier5';
}

export function getSourcesByCategory(
  category: ApiCategory | RssCategory | SitesCategory | SocialCategory | RumorsCategory,
  subCategory?: string
): Source[] {
  if (category in SOURCES_DATABASE.apis && subCategory) {
    return SOURCES_DATABASE.apis[category as ApiCategory] as unknown as Source[];
  }
  if (category in SOURCES_DATABASE.rss && subCategory) {
    return SOURCES_DATABASE.rss[category as RssCategory] as unknown as Source[];
  }
  if (category in SOURCES_DATABASE.sites && subCategory) {
    return SOURCES_DATABASE.sites[category as SitesCategory] as unknown as Source[];
  }
  if (category in SOURCES_DATABASE.social && subCategory) {
    return SOURCES_DATABASE.social[category as SocialCategory] as unknown as Source[];
  }
  if (category in SOURCES_DATABASE.rumors && subCategory) {
    return SOURCES_DATABASE.rumors[category as RumorsCategory] as unknown as Source[];
  }
  return [];
}

export function getAllSources(): Array<{ category: string; subCategory: string; source: Source }> {
  const allSources: Array<{ category: string; subCategory: string; source: Source }> = [];

  for (const [category, subCategories] of Object.entries(SOURCES_DATABASE)) {
    for (const [subCategory, sources] of Object.entries(subCategories as Record<string, Source[]>)) {
      for (const source of sources) {
        allSources.push({ category, subCategory, source });
      }
    }
  }

  return allSources;
}

export function getTotalSourceCount(): number {
  let count = 0;
  for (const category of Object.values(SOURCES_DATABASE)) {
    for (const subCategories of Object.values(category as Record<string, Source[]>)) {
      count += (subCategories as Source[]).length;
    }
  }
  return count;
}
